[general]
output_dir_tmpl = {{ build_root }}/wiredtiger_bug_1
verbose = yes
pm_fs_path = {{YOUR_PATH}}
max_nproc = 5
parallelize = no
sanity_test = no
fsync_test = no
op_tracing = no
count_crash_state = no
mode = posix
# test_ranges = [25-30]

[trace]
trace_path = {{ pwd }}/traces/tracer.log
root_dir = /home/yilegu/squint_test_dir/ba25-87e9-e867-a334
verbose = yes
cmd_tmpl = {{ WIREDTIGER_PATH }}/build/test/csuite/random_abort/test_random_abort -o 11 -T 1 -s workload -h {{ pmdir }}

[test]
checker_tmpl = {{ WIREDTIGER_PATH }}/build/test/csuite/random_abort/test_random_abort -o 11 -T 1 -s checker -h {{ pmdir }}
timeout = 30
