[general]
output_dir_tmpl = {{ build_root }}/rocksdb_bug_0
verbose = yes
pm_fs_path = {{YOUR_PATH}}
max_nproc = 80
parallelize = yes
sanity_test = no
fsync_test = no
op_tracing = no
max_um_size = 100
count_crash_state = no
mode = posix
# test_ranges = [185-195]

[trace]
trace_path = {{ pwd }}/traces/tracer.log
root_dir = /home/yilegu/squint_test_dir/89e8-380b-0376-4ba8
verbose = yes
cmd_tmpl = {{ pwd }}/workload {{ pmdir }}

[test]
checker_tmpl = {{ pwd }}/checker {{ pmdir }}
timeout = 300
