[general]
output_dir_tmpl = {{ build_root }}/wiredtiger_bug_0_persevere
verbose = yes
pm_fs_path = {{YOUR_PATH}}
max_nproc = 40
parallelize = yes
sanity_test = no
fsync_test = no
op_tracing = no
count_crash_state = no
persevere = yes
mode = posix
# test_ranges = [25-30]

[trace]
trace_path = {{ pwd }}/traces/tracer.log
root_dir = /home/yilegu/squint_test_dir/f846-87f3-5e33-bbfa
verbose = yes
cmd_tmpl = {{ pwd }}/workload {{ pmdir }}

[test]
checker_tmpl = {{ pwd }}/checker {{ pmdir }}/COPYDIR
timeout = 30